{% set version = "20150908" %}
{% set name = "m4rie" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://bitbucket.org/malb/m4rie/downloads/{{ name }}-{{ version }}.tar.gz
  sha256: 4bc3f53a5116e1ff0720c08f34ce415c88e2fb503437abfd15e196792ec6d5aa

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - libtool
    - libpng >=1.6.28,<1.7
    - zlib 1.2.*
    - m4ri
  run:
    - libpng >=1.6.28,<1.7
    - zlib 1.2.*
    - m4ri

test:
  commands:
    - test -f ${PREFIX}/include/m4rie/m4rie.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: https://bitbucket.org/malb/m4rie
  license: GPLv2+
  license_file: {{ SRC_DIR }}/COPYING
  summary: M4RIE is a library for fast arithmetic with dense matrices over GF(2^e) for 2 ≤ e ≤ 16.
  dev_url: https://bitbucket.org/malb/m4rie
  doc_url: https://malb.bitbucket.io/m4rie

extra:
  recipe-maintainers:
    - isuruf
