{% set version = "1.15.1" %}

package:
  name: quickfix-cpp
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/quickfix/quickfix/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1c4322a68704526ca3d1f213e7b0dcd30e067a8815be2a79b2ab1197ef70dcf7
  patches:
    - fix-unit-test.diff

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - libtool
    - m4
    - autoconf
    - automake
    - make
  host:
    - openssl

test:
  commands:
    - test -f $PREFIX/bin/quickfix

about:
  home: https://github.com/quickfix/quickfix/
  license: Apache-1.1
  license_family: Apache
  license_file: LICENSE
  summary: |
    The Financial Information Exchange (FIX) Protocol is a message standard 
    developed to facilitate the electronic exchange of information related 
    to securities transactions. It is intended for use between trading 
    partners wishing to automate communications.

    QuickFIX is a free and open source implementation of the FIX protocol.

extra:
  recipe-maintainers:
    - dillonroach
