{% set name = "spirv-headers" %}
{% set version = "1.3.243.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/sdk-{{ version }}.tar.gz
    sha256: 16927b1868e7891377d059cd549484e4158912439cf77451ae7e01e2a3bcd28b

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make    # [unix]
    - ninja   # [win]
  host:
  run:

test:
  commands:
    - spirv-as -h

about:
  home: https://github.com/KhronosGroup/SPIRV-Headers
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Machine-readable files for the SPIR-V Registry

extra:
  recipe-maintainers:
    - isuruf
