{% set name = "rpy2" %}
{% set version = "2.8.5" %}
{% set sha256 = "09c63bc934d666f4ec16e74caf52eb516e035557407a93591e8da694a1718ca6" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # windows doesn't compile
  skip: true  # [win]

requirements:
  build:
    - posix                  # [win]
    - {{ native }}toolchain  # [win]
    - gcc                    # [not win]
    - readline               # [not win]
    - python
    - setuptools
    - six
    - r-base
  run:
    - libgcc                 # [not win]
    - readline               # [not win]
    - python
    - six
    - r-base
    - singledispatch         # [py<34]

test:
  requires:
    - ipython
    - numpy
    - pandas
  imports:
    - rpy2
    - rpy2.interactive
    - rpy2.interactive.tests
    - rpy2.rinterface
    - rpy2.rinterface.tests
    - rpy2.ipython
    - rpy2.ipython.tests
    - rpy2.rlike
    - rpy2.rlike.tests
    - rpy2.robjects
    - rpy2.robjects.lib
    - rpy2.robjects.lib.tests
    - rpy2.robjects.tests

about:
  home: http://rpy2.bitbucket.org
  license: GPL-2.0
  license_family: GPL2
  # license_file gpl-2.0.txt
  summary: 'Python interface to the R language (embedded R)'
  description: |
    rpy2 is an interface to R running embedded in a Python process.
  doc_url: https://rpy2.readthedocs.io
  dev_url: https://bitbucket.org/rpy2/rpy2

extra:
  recipe-maintainers:
    - ceholden
    - johanneskoester
    - bgruening
    - isuruf
