{% set version = "0.2.3dev" %}
{% set name = "fpylll" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fplll/fpylll/archive/f8539b4640790e6e6b0d66456b83fd7d85cfb792.tar.gz
  sha256: e7d6bd7e94942a79bba577d50d37751823f871e08d2e7b249625b586d3747418

build:
  number: 0
  skip: true  # [win]
  script:
    # https://github.com/conda-forge/toolchain-feedstock/pull/11
    - export CPPFLAGS="-I${PREFIX}/include ${CPPFLAGS}"
    - python setup.py install

requirements:
  build:
    - toolchain
    - cython
    - pkg-config
    - gmp >=5.0.1,<7.0
    - mpfr >=3.*
    - fplll
    - cysignals
    - numpy x.x
    - python
  run:
    - gmp >=5.0.1,<7.0
    - mpfr >=3.*
    - fplll
    - cysignals
    - numpy x.x
    - python

test:
  requires:
    - pytest
  commands:
    - py.test -v
  imports:
    - fpylll
  source_files:
    - tests/*

about:
  home: https://github.com/fplll/fpylll
  license: GPLv2+
  license_file: LICENSE
  summary: A Python (2 and 3) wrapper for fplll.
  dev_url: https://github.com/fplll/fpylll

extra:
  recipe-maintainers:
    - isuruf
