{% set version = "5.0.3" %}
{% set name = "fplll" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fplll/fplll/archive/0d1e12bc89e41693167eb48b976e4fb920bbe5f8.tar.gz
  sha256: 6ab335381bd3fa08e860dbb9ae869d888723ce35856bf40964e8a94e6c1b8830

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - libtool
    - automake
    - m4
    - gmp
    - mpfr
  run:
    - gmp
    - mpfr

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: https://github.com/fplll/fplll
  license: LGPL v2+
  license_file: {{ SRC_DIR }}/COPYING
  summary: Lattice algorithms using floating-point arithmetic
  doc_url: https://fplll.github.io/fplll
  dev_url: https://github.com/fplll/fplll

extra:
  recipe-maintainers:
    - isuruf
