{% set name = "ghc" %}
{% set version = "8.2.1" %}
{% set sha256 = "07d06efa9222638c80b72ceda957d3c7bcbdc2665a9738dd6ef6c0751a05e8ed" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://downloads.haskell.org/~ghc/{{ version }}/ghc-{{ version }}-src.tar.xz

build:
  number: 0
  skip: True  # [osx]
  skip: True  # [win]

requirements:
  build:
    - toolchain3
    - pkg-config
    - perl          5.22.0.1
    - readline
    - gmp
    - ncurses
    - m4
    - curl
  run:
    - readline
    - gmp
    - ncurses

test:
  commands:
    - ghc --help > /dev/null

about:
  home: https://www.haskell.org/ghc/
  license: BSD
  summary: "GHC is a state-of-the-art, open source, compiler and interactive environment for the functional language Haskell."

extra:
  recipe-maintainers:
    - notestaff
  notes: "ghc 6.8.3 is outdated but needed to bootstrap the building of later versions"
